// ignore_for_file: depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:shared/models.dart';
import 'package:shared/providers/auth_provider.dart';
import 'package:trainer_app/home_screen.dart';
import 'package:trainer_app/login_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();

  // Register all adapters generated by build_runner
  Hive.registerAdapter(UserRoleAdapter());
  Hive.registerAdapter(MessageStatusAdapter());
  Hive.registerAdapter(CallRequestStatusAdapter());
  Hive.registerAdapter(UserAdapter());
  Hive.registerAdapter(MessageAdapter());
  Hive.registerAdapter(CallRequestAdapter());
  Hive.registerAdapter(SessionLogAdapter());
  Hive.registerAdapter(RoomMetaAdapter());

  // Open boxes
  await Hive.openBox('users');
  await Hive.openBox('messages');
  await Hive.openBox('call_requests');
  runApp(const ProviderScope(child: TrainerApp()));
}

class TrainerApp extends ConsumerWidget {
  const TrainerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final currentUser = ref.watch(authProvider);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Trainer App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFE50914),
        ), // Required Red
        scaffoldBackgroundColor: Colors.white,
        useMaterial3: true,
      ),
      // Router logic based on auth state
      home: currentUser == null ? const LoginScreen() : const HomeScreen(),
    );
  }
}
