// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shared/models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CallRequestAdapter());
    registerAdapter(CallRequestStatusAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageStatusAdapter());
    registerAdapter(RoomMetaAdapter());
    registerAdapter(SessionLogAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CallRequestAdapter());
    registerAdapter(CallRequestStatusAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageStatusAdapter());
    registerAdapter(RoomMetaAdapter());
    registerAdapter(SessionLogAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
