import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:guru_app/home_screen.dart';
import 'package:guru_app/onboarding_screen.dart';
import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:shared/models.dart';
import 'package:shared/providers/auth_provider.dart';
import 'package:shared/theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();

  // Register all adapters generated by build_runner
  Hive.registerAdapter(UserRoleAdapter());
  Hive.registerAdapter(MessageStatusAdapter());
  Hive.registerAdapter(CallRequestStatusAdapter());
  Hive.registerAdapter(UserAdapter());
  Hive.registerAdapter(MessageAdapter());
  Hive.registerAdapter(CallRequestAdapter());
  Hive.registerAdapter(SessionLogAdapter());
  Hive.registerAdapter(RoomMetaAdapter());

  // Open boxes
  await Hive.openBox('users');
  await Hive.openBox('messages');
  await Hive.openBox('call_requests');
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Guru App',
      theme: AppTheme.guruTheme,
      // theme: ThemeData(colorScheme: .fromSeed(seedColor: Colors.deepPurple)),
      home: const GuruApp(),
    );
  }
}

class GuruApp extends ConsumerWidget {
  const GuruApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final currentUser = ref.watch(authProvider);

    return MaterialApp(
      title: 'Guru App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1769E0),
        ), // Required Blue
        scaffoldBackgroundColor: Colors.white,
        useMaterial3: true,
      ),
      // Router logic based on auth state
      home: currentUser == null ? const OnboardingScreen() : const HomeScreen(),
    );
  }
}
